### ISSUE TITLE
[기능] Recent Diary에서 프로필 사진도 포함

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/backend#58]

**Comment by BambooKim** [comment]
## TODO
- [ ] `User` 엔티티에 `profileImage` 추가
  - [ ] 로그인 시 auth에서 받아온 profileImage랑 비교 후 다르면 update
  - [ ] `DiaryResponseDto.Recent`에 `profileImage` 필드 추가

**Comment by BambooKim** [comment]
@bluejoyq 프로필 사진 추가했습니다.

**Comment by bluejoyq** [comment]
체크해볼게요~
